<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9543" started-at="2016-10-25T04:46:41Z" finished-at="2016-10-25T04:46:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="9543" started-at="2016-10-25T04:46:41Z" finished-at="2016-10-25T04:46:51Z">
      <class name="Com.DataDrivenFramework.TestCases.DummyTestB">
        <test-method status="FAIL" signature="testB1()[pri:0, instance:Com.DataDrivenFramework.TestCases.DummyTestB@13acb0d1]" name="testB1" duration-ms="9191" started-at="2016-10-25T00:46:41Z" finished-at="2016-10-25T00:46:51Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Com.DataDrivenFramework.java.BaseTest.takeScreenShoot(BaseTest.java:298)
	at Com.DataDrivenFramework.TestCases.DummyTestB.testB1(DummyTestB.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB1 -->
        <test-method status="PASS" signature="testB2()[pri:0, instance:Com.DataDrivenFramework.TestCases.DummyTestB@13acb0d1]" name="testB2" is-config="true" duration-ms="330" started-at="2016-10-25T00:46:51Z" finished-at="2016-10-25T00:46:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB2 -->
      </class> <!-- Com.DataDrivenFramework.TestCases.DummyTestB -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
