<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Gerardos-MacBook-Pro.local" name="Com.DataDrivenFramework.TestCases.DummyTestB" tests="2" failures="0" timestamp="17 Oct 2016 20:47:04 GMT" time="5.665" errors="1">
  <testcase name="testB1" time="5.665" classname="Com.DataDrivenFramework.TestCases.DummyTestB"/>
  <testcase name="testB2" time="0.000" classname="Com.DataDrivenFramework.TestCases.DummyTestB">
    <error type="java.lang.Error" message="Unresolved compilation problems: 
	The method endTest(ExtentTest) is undefined for the type ExtentTest
	The method flush() is undefined for the type ExtentTest
">
      <![CDATA[java.lang.Error: Unresolved compilation problems: 
	The method endTest(ExtentTest) is undefined for the type ExtentTest
	The method flush() is undefined for the type ExtentTest

	at Com.DataDrivenFramework.TestCases.DummyTestB.testB2(DummyTestB.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.TestRunner.afterRun(TestRunner.java:980)
	at org.testng.TestRunner.run(TestRunner.java:611)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- testB2 -->
</testsuite> <!-- Com.DataDrivenFramework.TestCases.DummyTestB -->
